# Generated by Django 5.2 on 2025-05-05 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
